// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Lo1AlVJilmTNrYuOX0gNlML1Jms4l-M',
    appId: '1:300518473483:web:328997e0319f6499fb6c0e',
    messagingSenderId: '300518473483',
    projectId: 'blindreader-aee46',
    authDomain: 'blindreader-aee46.firebaseapp.com',
    storageBucket: 'blindreader-aee46.appspot.com',
    measurementId: 'G-42VZ926VH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUDM7BygzOJJ_x_Ffeyo7efcdcC7fe6Jk',
    appId: '1:300518473483:android:ec79019216069f6efb6c0e',
    messagingSenderId: '300518473483',
    projectId: 'blindreader-aee46',
    storageBucket: 'blindreader-aee46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV8jRMSaUmn8YX3gnvAykgSDgqxWnibWw',
    appId: '1:300518473483:ios:b634510b31b497bcfb6c0e',
    messagingSenderId: '300518473483',
    projectId: 'blindreader-aee46',
    storageBucket: 'blindreader-aee46.appspot.com',
    iosBundleId: 'com.example.blindreader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV8jRMSaUmn8YX3gnvAykgSDgqxWnibWw',
    appId: '1:300518473483:ios:d94524caae092991fb6c0e',
    messagingSenderId: '300518473483',
    projectId: 'blindreader-aee46',
    storageBucket: 'blindreader-aee46.appspot.com',
    iosBundleId: 'com.example.blindreader.RunnerTests',
  );
}
